name: Build Application

permissions: 
  contents: read

runs:
  using: 'composite'

  steps:
  - name: Checkout repository
    # run: git clone https://github.com/benlug/ml-prod-app.git
    uses: actions/checkout@v4


  - name: Set up Python 
    uses: actions/setup-python@v5
    with:
      python-version: 3.12

  - name: Install Poetry
    uses: snok/install-poetry@v1
    with:
      virtualenvs-in-project: true

  - name: load cached venv
    uses: actions/cache@v4
    id: cached-poetry-dependencies
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    run: poetry run make install

  - name: Lint with ruff
    run: poetry run make check

    